# Generated by Django 3.1.7 on 2021-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
