# Generated by Django 3.1.7 on 2021-03-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_player', '0003_class_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='select_player.class'),
        ),
    ]
